[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false
anchor-debug = true

[programs.localnet]
uni_grading = "edMGRxyFcpnGj5jqY6VPg4AyF3SJg9ybjjezgsJK33B"

[programs.devnet]
uni_grading = "edMGRxyFcpnGj5jqY6VPg4AyF3SJg9ybjjezgsJK33B"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 30000
shutdown_wait = 10000
